name: Custom / Approve

on:
  pull_request:
    branches:
      - main

env:
  FORCE_COLOR: 1

jobs:
  approve:
    name: Approve
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'pre-commit-ci[bot]'
    runs-on: ubuntu-latest
    environment:
      name: approve
      deployment: false
    steps:
      - id: auth
        name: Auth
        uses: liblaf/actions/auth@ba7e8a8be5abc0d1e1bac89ccc58f86204c06a20 # v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Enable Auto-merge
        run: >-
          gh pr edit '${{ github.event.pull_request.html_url }}' --add-label
          'automerge'
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Approve
        uses: liblaf/actions/approve@ba7e8a8be5abc0d1e1bac89ccc58f86204c06a20 # v3
        with:
          app: pre-commit-ci
          approve-token: ${{ steps.auth.outputs.token }}
          label: automerge
          reviewer: ${{ steps.auth.outputs.committer-name }}
