name: pre-commit config

on:
  push:
    paths:
      - .pre-commit-config.yaml
  workflow_dispatch:

jobs:
  copy:
    name: Copy
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Copy
        run: cp --target-directory='template' --verbose '.pre-commit-config.yaml'
      - name: Commit
        uses: liblaf/actions-ts/commit@dist
        with:
          message: >-
            chore(ci): update pre-commit config
